print("Please enter the following: ")
print()
adjective = input("adjective: ")
animal = input("animal: ")
verb_01 = input("verb: ")
exclamation = input("exclamation: ")
verb_02 = input("verb: ")
verb_03 = input("verb: ")
print()
print("Your story is:")
print()
print(f'The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective} {animal} {verb_01} down the hallway."{exclamation.capitalize()}"! I yelled. But all')
print(f'I could think to do was to {verb_02} over and over. Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb_03}')
print(f'right in front of my family.')